2024-04-03 07:28:09,306 INFO    MainThread:114365 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-04-03 07:28:09,306 INFO    MainThread:114365 [wandb_setup.py:_flush():76] Configure stats pid to 114365
2024-04-03 07:28:09,306 INFO    MainThread:114365 [wandb_setup.py:_flush():76] Loading settings from /home/surajracha/.config/wandb/settings
2024-04-03 07:28:09,306 INFO    MainThread:114365 [wandb_setup.py:_flush():76] Loading settings from /home/surajracha/ChatLLM/DataGen/Data/Gemini/Data2/Power-Mechanism-new/Forrest Cover Type/wandb/settings
2024-04-03 07:28:09,306 INFO    MainThread:114365 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-04-03 07:28:09,306 INFO    MainThread:114365 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-04-03 07:28:09,306 INFO    MainThread:114365 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-04-03 07:28:09,306 INFO    MainThread:114365 [wandb_init.py:_log_setup():526] Logging user logs to /home/surajracha/ChatLLM/DataGen/Data/Gemini/Data2/Power-Mechanism-new/Forrest Cover Type/wandb/run-20240403_072809-sdzitejj/logs/debug.log
2024-04-03 07:28:09,306 INFO    MainThread:114365 [wandb_init.py:_log_setup():527] Logging internal logs to /home/surajracha/ChatLLM/DataGen/Data/Gemini/Data2/Power-Mechanism-new/Forrest Cover Type/wandb/run-20240403_072809-sdzitejj/logs/debug-internal.log
2024-04-03 07:28:09,307 INFO    MainThread:114365 [wandb_init.py:_jupyter_setup():472] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f4b85f7b520>
2024-04-03 07:28:09,307 INFO    MainThread:114365 [wandb_init.py:init():566] calling init triggers
2024-04-03 07:28:09,307 INFO    MainThread:114365 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-04-03 07:28:09,307 INFO    MainThread:114365 [wandb_init.py:init():616] starting backend
2024-04-03 07:28:09,307 INFO    MainThread:114365 [wandb_init.py:init():620] setting up manager
2024-04-03 07:28:09,371 INFO    MainThread:114365 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-04-03 07:28:09,373 INFO    MainThread:114365 [wandb_init.py:init():628] backend started and connected
2024-04-03 07:28:09,375 INFO    MainThread:114365 [wandb_run.py:_label_probe_notebook():1295] probe notebook
2024-04-03 07:28:09,375 INFO    MainThread:114365 [wandb_run.py:_label_probe_notebook():1305] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-04-03 07:28:09,375 INFO    MainThread:114365 [wandb_init.py:init():720] updated telemetry
2024-04-03 07:28:09,383 INFO    MainThread:114365 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-04-03 07:28:10,088 INFO    MainThread:114365 [wandb_run.py:_on_init():2262] communicating current version
2024-04-03 07:28:10,139 INFO    MainThread:114365 [wandb_run.py:_on_init():2271] got version response upgrade_message: "wandb version 0.16.5 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2024-04-03 07:28:10,139 INFO    MainThread:114365 [wandb_init.py:init():804] starting run threads in backend
2024-04-03 07:28:12,893 INFO    MainThread:114365 [wandb_run.py:_console_start():2241] atexit reg
2024-04-03 07:28:12,894 INFO    MainThread:114365 [wandb_run.py:_redirect():2096] redirect: wrap_raw
2024-04-03 07:28:12,894 INFO    MainThread:114365 [wandb_run.py:_redirect():2161] Wrapping output streams.
2024-04-03 07:28:12,894 INFO    MainThread:114365 [wandb_run.py:_redirect():2186] Redirects installed.
2024-04-03 07:28:12,895 INFO    MainThread:114365 [wandb_init.py:init():847] run started, returning control to user process
2024-04-03 07:28:13,005 INFO    MainThread:114365 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-04-03 07:28:13,006 INFO    MainThread:114365 [wandb_init.py:_pause_backend():437] pausing backend
2024-04-03 07:28:19,678 INFO    MainThread:114365 [wandb_init.py:_resume_backend():442] resuming backend
2024-04-03 07:28:19,709 INFO    MainThread:114365 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-04-03 07:28:19,709 INFO    MainThread:114365 [wandb_setup.py:_flush():76] Configure stats pid to 114365
2024-04-03 07:28:19,709 INFO    MainThread:114365 [wandb_setup.py:_flush():76] Loading settings from /home/surajracha/.config/wandb/settings
2024-04-03 07:28:19,709 INFO    MainThread:114365 [wandb_setup.py:_flush():76] Loading settings from /home/surajracha/ChatLLM/DataGen/Data/Gemini/Data2/Power-Mechanism-new/Forrest Cover Type/wandb/settings
2024-04-03 07:28:19,709 INFO    MainThread:114365 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-04-03 07:28:19,709 INFO    MainThread:114365 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-04-03 07:28:19,710 INFO    MainThread:114365 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-04-03 07:28:19,710 INFO    MainThread:114365 [wandb_init.py:_log_setup():526] Logging user logs to /home/surajracha/ChatLLM/DataGen/Data/Gemini/Data2/Power-Mechanism-new/Forrest Cover Type/wandb/run-20240403_072819-7qmsvgmu/logs/debug.log
2024-04-03 07:28:19,710 INFO    MainThread:114365 [wandb_init.py:_log_setup():527] Logging internal logs to /home/surajracha/ChatLLM/DataGen/Data/Gemini/Data2/Power-Mechanism-new/Forrest Cover Type/wandb/run-20240403_072819-7qmsvgmu/logs/debug-internal.log
2024-04-03 07:28:19,710 INFO    MainThread:114365 [wandb_init.py:init():566] calling init triggers
2024-04-03 07:28:19,710 INFO    MainThread:114365 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-04-03 07:28:19,710 INFO    MainThread:114365 [wandb_init.py:init():591] re-initializing run, found existing run on stack: sdzitejj
2024-04-03 07:28:19,711 INFO    MainThread:114365 [wandb_run.py:_finish():1970] finishing run ponkshekaustubh11/covertype test/sdzitejj
2024-04-03 07:28:19,712 ERROR   MainThread:114365 [jupyter.py:save_history():437] Run pip install nbformat to save notebook history
2024-04-03 07:28:19,712 INFO    MainThread:114365 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-04-03 07:28:19,712 INFO    MainThread:114365 [wandb_init.py:_jupyter_teardown():454] cleaning up jupyter logic
2024-04-03 07:28:19,712 INFO    MainThread:114365 [wandb_run.py:_atexit_cleanup():2210] got exitcode: 0
2024-04-03 07:28:19,712 INFO    MainThread:114365 [wandb_run.py:_restore():2193] restore
2024-04-03 07:28:19,712 INFO    MainThread:114365 [wandb_run.py:_restore():2199] restore done
2024-04-03 07:28:23,926 INFO    MainThread:114365 [wandb_run.py:_footer_history_summary_info():3866] rendering history
2024-04-03 07:28:23,926 INFO    MainThread:114365 [wandb_run.py:_footer_history_summary_info():3898] rendering summary
2024-04-03 07:28:23,930 INFO    MainThread:114365 [wandb_run.py:_footer_sync_info():3825] logging synced files
